<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ufoahc</title>
    <link rel="shortcut icon" href="/ico/common/favicon.ico">
    <link rel="stylesheet" href="/css/common/base-rest.min.css" type="text/css" />
    <script src="/js/common/jquery.min.js"></script>
    <script src="/js/common/main.js"></script>
</head>
<body>
<div>这里是顶部,这是模板2</div>
<hr>
<div>
    <?php include $_content; ?>
</div>
<hr>
<div>这里是底部</div>
</body>
</html>